function job modify

diff --git a/jjb/genesis/genesis-foreman.yml b/jjb/genesis/genesis-foreman.yml
--- a/jjb/genesis/genesis-foreman.yml
+++ b/jjb/genesis/genesis-foreman.yml
@@ -11,10 +11,11 @@
 
     jobs:
         - 'genesis-foreman-verify-{stream}'
-        - 'genesis-foreman-merge'
+        - 'genesis-foreman-merge-{stream}'
         - 'genesis-foreman-daily-{stream}'
         - 'genesis-foreman-build-{stream}'
         - 'genesis-foreman-deploy-{stream}'
+        - 'genesis-foreman-deploy-runner-{stream}'
 
     # stream:    branch with - in place of / (eg. stable-arno)
     # branch:    branch (eg. stable/arno)
@@ -96,7 +97,7 @@
         - 'foreman-workspace-cleanup'
 
 - job-template:
-    name: 'genesis-foreman-merge'
+    name: 'genesis-foreman-merge-{stream}'
 
     project-type: freestyle
 
@@ -119,7 +120,7 @@
         - project-parameter:
             project: '{project}'
         - gerrit-parameter:
-            branch: 'master'
+            branch: '{branch}'
         - foreman-parameter:
             installer: '{installer}'
             gs-pathname: ''
@@ -144,7 +145,7 @@
                 project-pattern: 'genesis'
                 branches:
                     - branch-compare-type: 'ANT'
-                      branch-pattern: '**/master'
+                      branch-pattern: '**/{branch}'
                 file-paths:
                   - compare-type: ANT
                     pattern: 'common/**'
@@ -153,7 +154,7 @@
 
     builders:
         - 'foreman-build'
-        - 'foreman-workspace-cleanup'
+        - 'fuel-workspace-cleanup'
 
 - job-template:
     name: 'genesis-foreman-daily-{stream}'
@@ -163,6 +164,9 @@
     node: ericsson-build
 
     disabled: false
+
+    triggers:
+        - 'foreman-{stream}'
 
     parameters:
         - project-parameter:
@@ -184,15 +188,18 @@
 
     builders:
         - trigger-builds:
-          - project: 'genesis-foreman-build'
+          - project: 'genesis-foreman-build-{stream}'
             git-revision: true
             block: true
         - trigger-builds:
-          - project: 'genesis-foreman-deploy'
+          - project: 'genesis-foreman-deploy-runner-{stream}'
             git-revision: true
             block: true
         - trigger-builds:
           - project: 'functest-opnfv-jump-2'
+            block: true
+        - trigger-builds:
+          - project: 'yardstick-opnfv-jump-2'
             block: true
 
 - job-template:
@@ -223,6 +230,7 @@
     builders:
         - 'foreman-build'
         - 'foreman-upload-artifact'
+        - 'fuel-workspace-cleanup'
 
 - job-template:
     name: 'genesis-foreman-deploy-{stream}'
@@ -259,6 +267,45 @@
     builders:
         - 'foreman-deploy'
 
+- job-template:
+    name: 'genesis-foreman-deploy-runner-{stream}'
+
+    project-type: freestyle
+
+    disabled: false
+
+    node: master
+
+    logrotate:
+        daysToKeep: 30
+        numToKeep: 10
+        artifactDaysToKeep: -1
+        artifactNumToKeep: -1
+
+    parameters:
+        - project-parameter:
+            project: '{project}'
+        - foreman-parameter:
+            installer: '{installer}'
+            gs-pathname: '{gs-pathname}'
+        - string:
+            name: GIT_BASE
+            default: ssh://gerrit.opnfv.org:29418/$PROJECT
+            description: "Used for overriding the GIT URL coming from parameters macro."
+
+    scm:
+        - git-scm:
+            credentials-id: '{ssh-credentials}'
+            refspec: ''
+            branch: '{branch}'
+
+    builders:
+        - 'foreman-lab-reconfig'
+        - trigger-builds:
+          - project: 'genesis-foreman-deploy-{stream}'
+            git-revision: true
+            block: true
+
 ########################
 # parameter macros
 ########################
@@ -289,6 +336,83 @@
 ########################
 # builder macros
 ########################
+- builder:
+    name: 'foreman-lab-reconfig'
+    builders:
+        - shell: |
+            #!/bin/bash
+            set -o errexit
+            set -o nounset
+            set -o pipefail
+
+            # check to see if ucs login info file exists
+            if [ -e ~/.ssh/ucs_creds ];then
+              source ~/.ssh/ucs_creds
+            else
+              echo "Unable to find UCS credentials for LF lab reconfiguration...Exiting"
+              exit 1
+            fi
+
+            # clone releng
+            echo "Cloning releng repo..."
+            if ! GIT_SSL_NO_VERIFY=true git clone https://gerrit.opnfv.org/gerrit/releng; then
+              echo "Unable to clone releng repo...Exiting"
+              exit 1
+            fi
+
+            # log info to console
+            echo "Starting the lab reconfiguration for $INSTALLER..."
+            echo "--------------------------------------------------------"
+            echo
+
+            # create venv
+            $WORKSPACE/releng/utils/lab-reconfiguration/create_venv.sh
+
+            # disable nounset because 'activate' script contains unbound variable(s)
+            set +o nounset
+            # enter venv
+            source $WORKSPACE/releng/utils/lab-reconfiguration/venv/bin/activate
+            # set nounset back again
+            set -o nounset
+
+            # verify we are in venv
+            if [[ ! $(which python | grep venv) ]]; then
+              echo "Unable to activate venv...Exiting"
+              exit 1
+            fi
+
+            python $WORKSPACE/releng/utils/lab-reconfiguration/reconfigUcsNet.py -i $ucs_host -u $ucs_user -p $ucs_password -f $WORKSPACE/releng/utils/lab-reconfiguration/foreman.yaml
+
+            # while undergoing reboot
+            sleep 30
+
+            # check to see if slave is back up
+            ping_counter=0
+            ping_flag=0
+            while [ "$ping_counter" -lt 20 ]; do
+              if [[ $(ping -c 5 172.30.10.72) ]]; then
+                ping_flag=1
+                break
+              fi
+              ((ping_counter++))
+              sleep 10
+            done
+
+            if [ "$ping_flag" -eq 1 ]; then
+              echo "Slave is pingable, now wait 60 seconds for services to start"
+              sleep 60
+            else
+              echo "Slave did not come back up after reboot: please check opnfv-jump-2"
+              exit 1
+            fi
+
+            set +o nounset
+            deactivate
+
+            echo
+            echo "--------------------------------------------------------"
+            echo "Done!"
+
 - builder:
     name: 'foreman-build'
     builders:
@@ -379,6 +503,7 @@
             echo
             echo "--------------------------------------------------------"
             echo "Done!"
+            echo "Artifact is available as http://$GS_URL/opnfv-$OPNFV_ARTIFACT_VERSION.iso"
 
 - builder:
     name: 'foreman-workspace-cleanup'
@@ -392,3 +517,15 @@
             # delete everything that is in $WORKSPACE
             /bin/rm -rf $WORKSPACE
 
+########################
+# trigger macros
+########################
+- trigger:
+    name: 'foreman-master'
+    triggers:
+        - pollscm: '0 21 * * *'
+
+- trigger:
+    name: 'foreman-stable-arno'
+    triggers:
+        - pollscm: '0 3 * * *'
